apiVersion: v1
kind: Namespace
metadata:
  name: controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ghp-account
  namespace: controller
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ghp-role
rules:
  - apiGroups: [""]
    resources: [persistentvolumes]
    verbs: [get, list, watch, patch]
  - apiGroups: [""]
    resources: [persistentvolumeclaims]
    verbs: [get, list, watch, patch, create, delete]
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list, watch, create, delete]
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
  - apiGroups: [storage.k8s.io]
    resources: [storageclasses]
    verbs: [get, list, watch]

  - apiGroups: [k8s.viveksingh.dev]
    resources: [generichttppopulators]
    verbs: [get, list, watch]
  # (Alpha) Access to referencegrants is only needed when the CSI driver
  # has the CrossNamespaceVolumeDataSource controller capability.
  # In that case, lib-volume-populator requires "get", "list", "watch"
  # permissions  for "referencegrants" on "gateway.networking.k8s.io".
  #- apiGroups: ["gateway.networking.k8s.io"]
  #  resources: ["referencegrants"]
  #  verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ghp-binding
subjects:
  - kind: ServiceAccount
    name: ghp-account
    namespace: controller
roleRef:
  kind: ClusterRole
  name: ghp-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: controller
  name: controller
  namespace: controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: controller
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: controller
    spec:
      serviceAccountName: ghp-account
      containers:
      - image: viveksinghggits/generichttppopulator:0.1.0
        name: generichttppopulator
        resources: {}
        args:
          - "--mode=controller"
          - "--image=viveksinghggits/generichttppopulator:0.1.0"
          - "--namespace=controller"
status: {}
