apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 8Gi
  dataSourceRef:
    apiGroup: k8s.viveksingh.dev
    kind: GenericHTTPPopulator
    name: akcess-readme-pop
